export const proveedores = [
    {
        id              :   1,
        foto            :   '/static/proveedores/1.jpeg',
        nombre          :   "TRS",
        representante   :   "OLGA MARIA MARULANDA B.",
        direccion       :   'Calle 30 # 46-08',
        telefono        :   '(4) 2629285',
        ciudad          :   'Medellin - Colombia',
        celular         :   '(034) 3127675097',
        email           :   'olga.marulanda@trspartes.com',
        descripcion     :   'Reparacion, suministro de equipos y repuestos de sistemas aire acondicionado.'
    },
    {
        id              :   2,
        foto            :   '/static/proveedores/2.jpeg',
        nombre          :   "INGEMEEC",
        representante   :   "JULIAN JARAMILLO ROLDAN",
        direccion       :   'Calle 28  58A 59',
        telefono        :   '(57-4) 3221761',
        ciudad          :   'Bello - Antioquia',
        celular         :   '316 3065648 301 3798079',
        email           :   'servicios@ingemeec.com',
        descripcion     :   'Mantenimiento y reparación de equipos eléctricos, aire acondicionado, sistemas electromecánicos, sistemas de bombeo, puertas.'
    },
    {
        id              :   3,
        foto            :   '/static/proveedores/3.jpeg',
        nombre          :   "MAYORISTA DE MATERIALES",
        representante   :   "Ever Rojas",
        direccion       :   'Cra 50 # 41 – 85 Palace con Calle 41, Cl. 41',
        telefono        :   '6044488284 ext 115',
        ciudad          :   'Medellín, Antioquia',
        celular         :   '3104363217',
        email           :   'ever.rojas@mayoristademateriales.com',
        descripcion     :   'Suministro de materiales a nivel general.'
    },
    {
        id              :   4,
        foto            :   '/static/proveedores/4.jpeg',
        nombre          :   "HOME CENTER",
        representante   :   "MARIA CAMILA FLÓREZ CIRO",
        direccion       :   'Cobertura en toda Colombia',
        telefono        :   '',
        ciudad          :   'Medellín, Antioquia',
        celular         :   '(57) 3166909152',
        email           :   'solicitudsupplycc.fms.co@sodexo.com',
        descripcion     :   'Suministro de materiales a nivel general.'
    },    
    {
        id              :   5,
        foto            :   '/static/proveedores/5.jpeg',
        nombre          :   "LOS RESPRETO",
        representante   :   "LILIANA ANGELICA RUIZ",
        direccion       :   'Cra 65 # 29-15',
        telefono        :   '',
        ciudad          :   'Medellín, Antioquia',
        celular         :   '302228683',
        email           :   'lruiz@losrestrepo.com',
        descripcion     :   'Suministro de poleas y bandas, sistemas aire acondicionado.'
    },
    {
        id              :   6,
        foto            :   '/static/proveedores/6.jpeg',
        nombre          :   "CASA FERRETERA",
        representante   :   "LUCILA HERNANDES GARCIA",
        direccion       :   'Cra 48 N. 42 -93',
        telefono        :   '',
        ciudad          :   'Medellín, Antioquia',
        celular         :   '3113698229',
        email           :   'Industria106@casaferretera.com',
        descripcion     :   'Suministro de ferretería a nivel general.'
    },
    {
        id              :   7,
        foto            :   '/static/proveedores/7.jpeg',
        nombre          :   "Ancla ingeniería",
        representante   :   "ANDRES GRANADA",
        direccion       :   'Cl. 44 #74-54',
        telefono        :   '',
        ciudad          :   'Medellín, Antioquia',
        celular         :   '3116864283',
        email           :   'anclaingenieros@gmail.com',
        descripcion     :   'Construcción de obras civiles, estructuras metálica entre otros'
    },
    {
        id              :   8,
        foto            :   '/static/proveedores/8.jpeg',
        nombre          :   "Llaves Medellin",
        representante   :   "Paola Andrea Salazar",
        direccion       :   'Cll 44# 9.135',
        telefono        :   '',
        ciudad          :   'Medellín, Antioquia',
        celular         :   '30537764259',
        email           :   'contabilidad@llavesmedellin.com',
        descripcion     :   'Copias de llaves, suministro y reparación de chapas'
    },
    {
        id              :   9,
        foto            :   '/static/proveedores/9.jpeg',
        nombre          :   "Equielec",
        representante   :   "Álvaro Javier Restrepo",
        direccion       :   'Carrera 72 # 30 - 53',
        telefono        :   '444-31-33',
        ciudad          :   'Medellín, Antioquia',
        celular         :   '3117205976',
        email           :   'alvarorestrepo@equielect.com.co',
        descripcion     :   'Suministro de sistemas eléctrico, repuestos, clavijas, cables, iluminación entre otros'
    }
]