import Head from 'next/head'
import Layout from '../components/Layout/Layout'
import Image from 'next/image'
import riseImagen from '../assets/Rise-with-Sodexo_1584x480px.jpg'
import miEntornoSeguro from '../assets/65785646_1134615796724879_1193037083267039232_n.jpg'
import tengoEquipCompleto from '../assets/65907437_1134615783391547_8320030166990454784_n.jpg'
import conozcoRiesgos from '../assets/65545155_1134615773391548_6331237924125802496_n.jpg'




export default function Home() {
  return (
    <Layout> 
      <div >
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className='flex'>
        <div className="relative" >
            <Image src={riseImagen} alt="riseSodexo" ></Image>
        </div>
          <div className="max-w-xs absolute bg-slate-50">
              <h1 className='font-bold'>Paginas Web</h1>

              <a className="block underline text-blue-500" href='https://sodexo-na.maximo.com/maximo/webclient/login/login.jsp?welcome=true' target="_blank" rel="noreferrer" >Maximo</a>
              <a className="block underline text-blue-500" href='https://smartrent.sodexhochile.cl/' target="_blank" rel="noreferrer" >Preaxion</a>
              <a className="block underline text-blue-500" href='https://prd-co-nom-sdx.sodexoaplicaciones.com/' target="_blank" rel="noreferrer" >Somos ya</a>
              <a className="block underline text-blue-500" href='https://ingresosonline.argos.co/' target="_blank" rel="noreferrer" >Ingresos online</a>
              <a className="block underline text-blue-500" href='https://www.iconstruye.com.co/includes/inicio.aspx?ReturnUrl=%2f' target="_blank" rel="noreferrer" >Iconstruye</a>
              <h1 className='font-bold'>Espíritu de Servicio</h1>
              <div className="mr-5  text-justify">
                <text>satisfacer las necesidades particulares de nuestros Clientes y Consumidores, haciendo de la interacción con ellos una experiencia memorable para asegurar el éxito de nuestra misión “Mejorar la calidad de vida diaria”.
                Espíritu de Equipo
                Las habilidades y cualidades de cada persona se combinan con las de otros miembros del equipo de trabajo, asegurando así el éxito de Sodexo.
                El trabajo en equipo está basado en el respeto hacia los otros, respeto de las reglas, ayuda mutua y capacidad de escuchar
                .</text>
                <br/>
                <h1 className='font-bold'>Espíritu de Progreso</h1>
                <text>
                La voluntad, pero además, la fuerte convicción de que podemos mejorar la situación presente.
                  La autocrítica, la certeza de que cada problema tiene solución, aceptación de evaluar nuestras competencias y compararlas con colegas y/o competidores.
                </text>
              </div>
              
          </div>
          <div className="self-end items-end flex flex-col">
            <Image src={miEntornoSeguro} width={350} height={350} alt="miEntornoSeguro" ></Image>
            <Image src={tengoEquipCompleto} width={350} height={350} alt="miEntornoSeguro" ></Image>
            <Image src={conozcoRiesgos} width={350} height={350} alt="conozcoRiesgos" ></Image>
          </div>
        </div>
      </div>
    </Layout>
  )
}
